---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dstestmohitrai/public_html/
   - /bin/cp home/dstestmohitrai/public_html/design/backend/templates/addons/jmj_digital/views/auth/seller_register.tpl $DEPLOYPATH